apiVersion: vedratan.dev/v1alpha1
kind: Kluster
metadata:
  name: kluster-0
  labels:
    # kyverno.io/ttl: "2023-08-04T003000Z"
    # kyverno.io/ttl:  "2022-08-04T00:30:00Z"
    kyverno.io/ttl: 10s
spec:
  name: kluster-0
  region: "nyc1"
  version: "1.14.1-do.4"
  tokenSecret: "default/dosecret"
  nodePools:
    - count: 3
      name: "dummy-nodepool"
      size: "s-2vcpu-2gb"